= Import / Export

MicroStream provides an API to import and export persisted data of the storage.
It is pretty much the same as writing and reading a backup.

The records in the storage are distributed in lots of files and folders, depending on channel count and other xref:configuration/properties.adoc[settings].
To get order in the chaos the export produces one file per type.
This files are used again by the import to read the data into the storage.

image:export.svg[]

NOTE: The created binary type data files contain only records of the according type, nevertheless they have the same format as the channel storage files.

[source, java, title="Export"]
----
// Setup file system and storage, used in all examples below
NioFileSystem          fileSystem = NioFileSystem.New();
EmbeddedStorageManager storage    = EmbeddedStorage.start(
	fileSystem.ensureDirectoryPath("storage")
);

StorageConnection                 connection   = storage.createConnection();
StorageEntityTypeExportStatistics exportResult = connection.exportTypes(
	fileSystem.ensureDirectoryPath("export-dir")
);
----

[source, java, title="Import"]
----
connection.importFiles(exportResult.files());
----

== Data Conversion

It is also possible to convert the exported binary files to a human readable format, namely CSV.

[NOTE]
====
 Why CSV?

Contrary to XML or JSON, CSV is perfectly suited to represent records with the least possible overhead.
There are a lot of tools, like spreadsheet editors, which can read and modify CSV files.
The file's size is at the possible minimum and the performance of the converter is significantly better than with the other formats.
====

[source, java, title="Binary to CSV"]
----
StorageDataConverterTypeBinaryToCsv converter = StorageDataConverterTypeBinaryToCsv.New(
    fileSystem.ensureDirectoryPath("csv-dir"),
    storage.typeDictionary()
);
converter.convertDataFiles(exportResult.files());
----

[source, java, title="CSV to Binary"]
----
StorageDataConverterTypeCsvToBinary<AFile> converter =
    StorageDataConverterTypeCsvToBinary.New(
        storage.typeDictionary(),
        fileSystem.ensureDirectoryPath("csv-dir")
);
converter.convertCsv(fileSystem.ensureFilePath("type1.csv"));
----
